# Generated by Django 6.0.1 on 2026-01-25 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='seals',
            name='minStock',
            field=models.IntegerField(default=5),
        ),
    ]
