# Generated by Django 6.0.1 on 2026-01-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0002_seals_minstock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sealName', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
                ('sold_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date_sold', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='seals',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
