# Generated by Django 6.0.1 on 2026-01-26 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0003_sale_alter_seals_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='date_sold',
        ),
    ]
