# Generated by Django 6.0.1 on 2026-01-26 15:21

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0004_remove_sale_date_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='date_sold',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
