# Generated by Django 6.0.1 on 2026-02-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0005_sale_date_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='sealName',
        ),
        migrations.RemoveField(
            model_name='seals',
            name='nameOfSeal',
        ),
        migrations.AddField(
            model_name='sale',
            name='partCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seals',
            name='minStock',
            field=models.IntegerField(default=500),
        ),
        migrations.AlterField(
            model_name='seals',
            name='partCode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
