# Generated by Django 6.0.1 on 2026-02-14 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0006_remove_sale_sealname_remove_seals_nameofseal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seals',
            name='description',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
