# Generated by Django 6.0.1 on 2026-02-14 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seals', '0007_alter_seals_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='partCode',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='seals',
            name='partCode',
            field=models.CharField(max_length=100),
        ),
    ]
